buildscript {
    repositories {
        mavenLocal()
        maven { url 'https://jitpack.io' }
        mavenCentral()
        google()
    }
    dependencies {
        classpath "org.junit.platform:junit-platform-gradle-plugin:1.0.0-M4"
    }
}

allprojects {
    apply plugin: 'java'
    apply plugin: 'maven-publish'
    apply plugin: 'jacoco'


    repositories {
        mavenLocal()
        maven { url 'https://jitpack.io' }
        mavenCentral()
        google()
    }
}

repositories {
    mavenCentral()
}

dependencies {
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'    
}


subprojects {
    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.3.1'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.3.1'    
    }

    test.useTestNG()
}

test {
    useJUnitPlatform()
}

jacoco {
    toolVersion = "0.8.5"
}

task codeCoverageReport(type: JacocoReport) {
    executionData fileTree(project.rootDir.absolutePath).include("**/build/jacoco/*.exec")

    subprojects.each {
        sourceSets it.sourceSets.main
    }
}

codeCoverageReport.dependsOn {
    subprojects*.test
}

dependencyLocking {
    lockAllConfigurations()
}